---
version: 2
updates:
  # workflows
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "daily"

  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: "daily"
